version: '3.4'

services:
  jobscatalogapi:
    image: ${DOCKER_REGISTRY-}jobscatalogapi
    build:
      context: .
      dockerfile: JobsCatalogApi/JobsCatalogApi/Dockerfile
    ports:
        - "7000:80"
    depends_on: 
        - "seq_logs"

  seq_logs:
    image: datalust/seq
    ports:
        - "8000:80"
    environment: 
        - ACCEPT_EULA=Y